jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v6
      - name: Setup
        run: luarocks install luacheck
      - name: Run luacheck
        run: luacheck netrc.lua tests
      - name: Install dependencies (Yarn)
        run: yarn
      - name: Check formatting
        run: yarn check-formatting
      - name: Check spelling
        run: yarn check-spelling
    strategy:
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4']
name: QA
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
